In [11]:
from mxnet import gluon, nd
from mxnet.gluon import nn

In [12]:
class CenteredLayer(nn.Block):
    def __init__(self, **kwargs):
        super(CenteredLayer, self).__init__(**kwargs)

    def forward(self, x):
        return x - x.mean()

In [13]:
layer = CenteredLayer()
layer(nd.array([1, 2, 3, 4, 5]))


[-2. -1.  0.  1.  2.]
<NDArray 5 @cpu(0)>

In [14]:
net = nn.Sequential()
net.add(nn.Dense(128),
        CenteredLayer())

In [15]:
net.initialize()
y = net(nd.random.uniform(shape=(4, 8)))
y.mean().asscalar()

5.338734e-10

In [16]:
params = gluon.ParameterDict()
params.get('param0', shape=(2, 3))
params

(
  Parameter param0 (shape=(2, 3), dtype=<class 'numpy.float32'>)
)

In [17]:
class MyDense(nn.Block):
    def __init__(self, units, in_units, **kwargs):
        super(MyDense, self).__init__(**kwargs)
        self.weight = self.params.get('weight', shape=(in_units, units))
        self.bias = self.params.get('bias', shape=(units,))

    def forward(self, x):
        linear = nd.dot(x, self.weight.data()) + self.bias.data()
        return nd.relu(linear)

In [18]:
dense = MyDense(units=3, in_units=5)
dense.params

mydense3_ (
  Parameter mydense3_weight (shape=(5, 3), dtype=<class 'numpy.float32'>)
  Parameter mydense3_bias (shape=(3,), dtype=<class 'numpy.float32'>)
)

In [19]:
dense.initialize()
dense(nd.random.uniform(shape=(2, 5)))


[[0.05768032 0.         0.02358942]
 [0.07314701 0.         0.07557119]]
<NDArray 2x3 @cpu(0)>

In [20]:
net = nn.Sequential()
net.add(MyDense(8, 64),
        MyDense(1, 8))

net.initialize()
net(nd.random.uniform(shape=(5, 64)))    


[[0.00599511]
 [0.00923245]
 [0.00562803]
 [0.00702969]
 [0.0128256 ]]
<NDArray 5x1 @cpu(0)>