In [5]:
from mxnet import nd
import d2lzh as d2l

In [6]:
X = nd.random.uniform(shape=(2, 3, 5))
X


[[[0.5204775  0.7805292  0.67887956 0.11827442 0.7206327 ]
  [0.639921   0.5820198  0.14335328 0.53737324 0.9446689 ]
  [0.7586156  0.5218483  0.1059076  0.41466194 0.47360042]]

 [[0.2645556  0.18633235 0.7742337  0.73691815 0.45615032]
  [0.21655035 0.56843394 0.13521817 0.0187898  0.324141  ]
  [0.6176355  0.14967486 0.6120957  0.22232139 0.616934  ]]]
<NDArray 2x3x5 @cpu(0)>

In [7]:
X = nd.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
              
K = nd.array([[[0, 1], [2, 3]], [[1, 2], [3, 4]]])

In [11]:
X.shape, K.shape # (2 3 3), ( 2 2 2)

((2, 3, 3), (2, 2, 2))

In [14]:
zipp = zip(X, K)
for x, k in zipp:
    y = d2l.corr2d(x, k)
    print(y)


[[19. 25.]
 [37. 43.]]
<NDArray 2x2 @cpu(0)>

[[37. 47.]
 [67. 77.]]
<NDArray 2x2 @cpu(0)>


In [29]:
out = nd.add_n(*[d2l.corr2d(x, k) for x, k in zip(X, K)])

In [30]:
out


[[ 56.  72.]
 [104. 120.]]
<NDArray 2x2 @cpu(0)>

In [28]:
*[d2l.corr2d(x, k) for x, k in zip(X, K)]

SyntaxError: can't use starred expression here (<ipython-input-28-def9dbed0b31>, line 4)

In [39]:
X = nd.random.uniform(shape=(3,3,3))
K = nd.random.uniform(shape=(2,3,1,1))

_X = X.reshape((3, 9))
_K = K.reshape((2,3))

In [40]:
_X, _K

(
 [[0.56660146 0.8651026  0.2653895  0.50896895 0.5232481  0.91672295
   0.0939405  0.9211576  0.5759465 ]
  [0.08311249 0.9292962  0.27771857 0.31856894 0.0093567  0.6674104
   0.8423421  0.13179787 0.6471741 ]
  [0.7163272  0.84138614 0.2894061  0.26473016 0.18319136 0.39782074
   0.5865129  0.55282146 0.02010755]]
 <NDArray 3x9 @cpu(0)>, 
 [[0.16494046 0.82894003 0.3698081 ]
  [0.00469548 0.14644176 0.6778165 ]]
 <NDArray 2x3 @cpu(0)>)

In [41]:
X, K

(
 [[[0.56660146 0.8651026  0.2653895 ]
   [0.50896895 0.5232481  0.91672295]
   [0.0939405  0.9211576  0.5759465 ]]
 
  [[0.08311249 0.9292962  0.27771857]
   [0.31856894 0.0093567  0.6674104 ]
   [0.8423421  0.13179787 0.6471741 ]]
 
  [[0.7163272  0.84138614 0.2894061 ]
   [0.26473016 0.18319136 0.39782074]
   [0.5865129  0.55282146 0.02010755]]]
 <NDArray 3x3x3 @cpu(0)>, 
 [[[[0.16494046]]
 
   [[0.82894003]]
 
   [[0.3698081 ]]]
 
 
  [[[0.00469548]]
 
   [[0.14644176]]
 
   [[0.6778165 ]]]]
 <NDArray 2x3x1x1 @cpu(0)>)

In [ ]:
# ......

In [42]:
def corr2d_multi_in(X, K):
    return nd.add_n(*[d2l.corr2d(x, k) for x, k in zip(X, K)])

In [43]:
def corr2d_multi_in_out(X, K):
    return nd.stack(*[corr2d_multi_in(X, k) for k in K])

In [44]:
def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h*w))
    K = K.reshape((c_o, c_i))
    Y = nd.dot(K, X)

    return Y.reshape((c_o, h, w))

In [47]:
X = nd.random.uniform(shape=(3,3,3))
K = nd.random.uniform(shape=(2,3,1,1))

Y1 = corr2d_multi_in_out_1x1(X, K)
Y2 = corr2d_multi_in_out(X, K)

In [49]:
Y1 - Y2


[[[ 0.0000000e+00 -1.1920929e-07  0.0000000e+00]
  [ 0.0000000e+00  0.0000000e+00 -5.9604645e-08]
  [ 0.0000000e+00  0.0000000e+00 -1.1920929e-07]]

 [[ 0.0000000e+00 -2.9802322e-08 -1.4901161e-08]
  [ 0.0000000e+00  0.0000000e+00 -1.4901161e-08]
  [ 0.0000000e+00  2.9802322e-08  2.9802322e-08]]]
<NDArray 2x3x3 @cpu(0)>